### ISSUE TITLE
lxml.etree.XPathEvalError: Invalid expression

### ISSUE THREAD

**Issue by ghost** [dpwrussell/columbus_assay_def_xml_to_csv#1]
Tried to run the script on one of Sharon's layout files. This was the result: 
jc168@Jays-iMac ~/Checkout/columbus_assay_def_xml_to_csv (master)
$ python convert_xml_to_csv.py ~/Downloads/2015-03-27exp.xml > ~/Desktop/2015-03-27exp.csv
Traceback (most recent call last):
  File "convert_xml_to_csv.py", line 118, in <module>
    main()
  File "convert_xml_to_csv.py", line 115, in main
    convert_file(f)
  File "convert_xml_to_csv.py", line 66, in convert_file
    namespaces=namespaces)
  File "lxml.etree.pyx", line 2186, in lxml.etree._ElementTree.xpath (src/lxml/lxml.etree.c:60010)
  File "xpath.pxi", line 359, in lxml.etree.XPathDocumentEvaluator.__call__ (src/lxml/lxml.etree.c:152734)
  File "xpath.pxi", line 227, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:151097)
  File "xpath.pxi", line 213, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:150950)
lxml.etree.XPathEvalError: Invalid expression

**Comment by dpwrussell** [comment]
Can you send me the file so I can recreate?

Thanks

**Comment by dpwrussell** [comment]
Fixed in 0a28768dd0f5aed37912e9fe2b164238cce26889 and ba77a3ce23b038995fd76295550df0f77864290c
